sandbox = {};
file_details={};
username='';

/****** Loading JSNB *********/
send_nb_to_sandbox=function(nb){
      const message = {
        action:"load_jsnb",
        data:nb,
        call_bk:""
      };
      
      sandbox.contentWindow.postMessage(message, '*');
}
load_jsnb=function(content){
      
      if(typeof(content)=='string') var nb=JSON.parse(content);      
      else var nb=content;
	send_nb_to_sandbox(nb);
      

      var run_on_load = nb.run_on_load || false;
      get_dom("nb_name").innerHTML=nb.metadata.name;
      document.title = nb.metadata.name+":  Scribbler JavaScript Notebook";
      var metaDescription = document.querySelector('meta[name="description"]');

	// Set the description dynamically
	var newDescription = nb.metadata.name+" - Notebook for experimenting in JavaScript. Contains editable code and output. Play with html and code using a simple interface - Scribbler.";
	metaDescription.setAttribute("content", newDescription);
      get_dom("run_on_load").checked=run_on_load;
     
	

}

load_file_click=async function() {
	
	
	const content = await load_file();
	
	get_dom("sandbox").setAttribute("sandbox","allow-scripts allow-downloads allow-top-navigation allow-popups");
        get_dom("sandbox").setAttribute("src","sandbox.html?var=xxx");
      	get_dom("break-sandbox").style.display='inline';
      	sandbox=await wait_for_dom("sandbox");
      	sandbox.addEventListener("load", function() {
	  load_jsnb(content);
	},{once:true});

}
load_from_url=function(){
	var url='';
	try{ 
		const urlParams = new URLSearchParams(window.location.search);
	const jsnb_path = urlParams.get('jsnb');
	if(jsnb_path !=null && typeof jsnb_path!=='undefined') url=jsnb_path;
		else url=window.location.href.split("#")[1];
	} catch(e){url="./examples/Hello-world.jsnb"}
	if(url==undefined) url="./examples/Hello-world.jsnb";
  	if( url.length>1){
  		if(url.split(":")[0].trim()=='github') initialize_from_git(url.split(":")[1].trim());
  		else read_file(url,load_jsnb,err=>{alert(err.message)});
  	}else{

  		
  		get_dom("nb_name").innerHTML="New JSNB";
  		insert_cell("code");
  	}
}

/***** Downloading ************/
// Sets up a new MessageChannel
// so we can return a Promise with the nb
function get_nb() {
  return new Promise((resolve) => {
    const channel = new MessageChannel();
    // this will fire when iframe will answer

    channel.port1.onmessage = e => {
    	var nb=e.data;
    	nb['run_on_load'] = get_dom("run_on_load").checked;
	nb.metadata.name=get_dom("nb_name").innerHTML;
    	return resolve(nb);
    }
    // let iframe know we're expecting an answer
    // send it its own port
    sandbox.contentWindow.postMessage({"action":'get_nb'}, '*', [channel.port2]);  
  });
}


// Sets up a new MessageChannel
// so we can return a Promise with the html
function get_html(view) {
  return new Promise((resolve) => {
    const channel = new MessageChannel();
    // this will fire when iframe will answer

    channel.port1.onmessage = e => {
    	var doc=e.data;
    	return resolve(doc);
    }
    // let iframe know we're expecting an answer
    // send it its own port
    sandbox.contentWindow.postMessage({"action":'get_html',"view":view}, '*', [channel.port2]);  
  });
}
download_js=async function(){
 	var nb =await get_nb();
	var js=nb.cells.filter(x=>x.type=='code').map(x=>x['code']);
 	js=js.join("\n/*---------*/\n");
 	js="/*Generated by JSNB: https://github.com/gopi-suvanam/jsnb*/\n\n"+js;
 	let file_name=get_dom("nb_name").innerHTML.replaceAll(' ','_')+'.js';
 	download_string(js,file_name,"data:text/js;charset=utf-8");
 	
}

download_html=async function(view){
	// Send a message object to the iframe
	var doc=await get_html(view);
	doc=doc.replace("______title",get_dom("nb_name").innerHTML);
	let file_name=get_dom("nb_name").innerHTML.replaceAll(' ','_')+'.html';
	download_string(doc,file_name,"data:text/html;charset=utf-8");
   
}
download_nb=async function(){
	// Send a message object to the iframe
	var nb=await get_nb();
	let url='';
	let file_name='';
	try{ 
	
		const urlParams = new URLSearchParams(window.location.search);
		const jsnb_path = urlParams.get('jsnb');
		if(jsnb_path !=null && typeof jsnb_path!=='undefined') url=jsnb_path;
			else url=window.location.href.split("#")[1];
	} catch(e){
		console.log(e);
		url=''
	}
		
	if(url!=undefined && url.length>1){
		 file_name = url.split('/').slice(-1)[0]
	}else{
		
		 file_name=nb.metadata.name.replaceAll(' ','_')+'.jsnb'
	}
	download_string(JSON.stringify(nb,undefined,2),file_name,"data:text/json;charset=utf-8");	
	
   
}

/****** Other Functionality ************/
run_all=function(){

    // Send a message object to the iframe
   
      const message = {
        action:"run_all",
        data:""      
       };
      sandbox.contentWindow.postMessage(message, '*');

}

insert_cell=function(type){
	 // Send a message object to the iframe
   
      const message = {
        action:"insert_cell",
        data:{type:type},
        call_bk:""
      };
      sandbox.contentWindow.postMessage(message, '*');
}
break_sandbox=async function(){
      const confirmation = confirm("!!! Alert !!! You are about to break the Sandbox. This can give the notebook access to your cookies, cache etc. Do so only if you trust the code in the notebook !!!");
      if(!confirmation) return;
      let nb=await get_nb();
      get_dom("sandbox").removeAttribute("sandbox");
      get_dom("sandbox").setAttribute("src","sandbox.html");
      
      sandbox=await wait_for_dom("sandbox")
      sandbox.addEventListener("load",async function(){
      		console.log("Sanbox loaded");
      		
      		load_jsnb(nb);
      		
      	}
      	,{once:true}
      );
      get_dom("break-sandbox").style.display='none';
}

/********* Initialize Certain Globa Variables and Load the JSNB from URL *****/
key_up=function(e) {
	  if (e.ctrlKey && e.key === 's') {
	    download_nb();
	  } else if (e.ctrlKey && e.key === 'g') {
	    openModal(get_dom('git-import-export'));
	  } else if (e.ctrlKey && e.key === 'o') {
	    load_file_click()
			
	  }
	  else if (e.altKey && e.key === '®') {
	    run_all()
			
	  }
	  else if (e.altKey && e.key === 'r') {
	    run_all()
			
	  }
	}
insitialize_page=async function(){

	window.onload = async function() {
		first_load=true;
		get_dom("sandbox").setAttribute("sandbox","allow-scripts allow-downloads allow-top-navigation allow-popups");
		get_dom("sandbox").setAttribute("src","sandbox.html");
		get_dom("break-sandbox").style.display='inline';
	      	
	      	
		sandbox = await wait_for_dom('sandbox');
		
		sandbox.addEventListener("load", function() {
			if(first_load){
				console.log("Loading from URL");
				load_from_url();
			}else{
				console.log("Ignoring");
			}
			first_load=false;
		},{once:true});
		
		
	  	document.onkeyup = key_up;
		
		sandbox.onkeyup=key_up;
		initialize_git();
	};
	
	  	
}

